# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20170719_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtype',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
