# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0002_auto_20170404_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
