# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0004_auto_20170405_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street1',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street2',
        ),
    ]
