# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0006_auto_20170406_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdrress',
            new_name='ShippingAddress',
        ),
    ]
