# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20170511_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description2',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
