# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facepackwizard', '0004_auto_20170324_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('helper', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.FileField(upload_to='images/base/')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFacePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('helper', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.FileField(upload_to='images/ingredients/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('helper', models.CharField(blank=True, max_length=1000)),
                ('createdte', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MixingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('helper', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.FileField(upload_to='images/mixing_agents/')),
                ('skin_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType')),
            ],
        ),
        migrations.CreateModel(
            name='PrePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlights', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('who', models.CharField(blank=True, max_length=5000, null=True)),
                ('made_with', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrePackIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient')),
                ('prepack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PrePack')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient')),
                ('skin_concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinConcern')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType')),
            ],
        ),
        migrations.CreateModel(
            name='SkinTypeConcernIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient')),
                ('skin_concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinConcern')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType')),
            ],
        ),
        migrations.CreateModel(
            name='SkinTypeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType')),
            ],
        ),
        migrations.CreateModel(
            name='FacePack',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Item')),
                ('image', models.FileField(null=True, upload_to='images/prepacks/')),
                ('made_with', models.CharField(blank=True, max_length=5000, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Base')),
                ('mixing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MixingAgent')),
            ],
            bases=('home.item',),
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='optional_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient'),
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.QuestionnaireUserData'),
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Recipe'),
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prepack',
            name='facepack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FacePack'),
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='facepack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FacePack'),
        ),
    ]
