# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facepack',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facepack',
            name='item',
        ),
        migrations.AddField(
            model_name='facepack',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Item'),
            preserve_default=False,
        ),
    ]
