# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_prepack_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepackingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='prepackingredients',
            name='prepack',
        ),
        migrations.RemoveField(
            model_name='prepack',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='prepack',
            name='made_with',
        ),
        migrations.RemoveField(
            model_name='prepack',
            name='who',
        ),
        migrations.AddField(
            model_name='prepack',
            name='ingredient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrePackIngredients',
        ),
    ]
