# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170720_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePackIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='prepack',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='prepack',
            name='highlights',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='prepack',
            name='made_with',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='prepack',
            name='who',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='prepackingredients',
            name='prepack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PrePack'),
        ),
    ]
