# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170324_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFacePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FacePack',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Item')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Base')),
                ('mixing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MixingAgent')),
            ],
            bases=('home.item',),
        ),
        migrations.CreateModel(
            name='PrePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facepack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FacePack')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='facepack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FacePack'),
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='optional_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient'),
        ),
        migrations.AddField(
            model_name='customfacepack',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Recipe'),
        ),
    ]
