# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0009_remove_item_real_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='real_type',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
