# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_intense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='price_regular',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
