# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170801_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=34.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_intense',
            field=models.DecimalField(decimal_places=2, default=48.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_regular',
            field=models.DecimalField(decimal_places=2, default=29.0, max_digits=6),
        ),
    ]
