# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0004_auto_20170324_1818'),
        ('home', '0012_customfacepack_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinTypeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ingredient')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType')),
            ],
        ),
    ]
