# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_skintypeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
