# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='mixingagent',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
