# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_skintypeconcerningredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfacepack',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Recipe'),
        ),
    ]
