# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170502_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='facepack',
            name='image',
            field=models.FileField(null=True, upload_to='images/prepacks/'),
        ),
    ]
