# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170512_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facepack',
            name='description',
        ),
    ]
