# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_facepack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facepack',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
