# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='images/ingredients/')),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
