# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='fp',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),

    ]
