# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170724_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='subtype',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
