# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='tracking',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='tracking',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
