# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20170824_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='subtype',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
