# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20170824_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='tracking',
        ),
    ]
