# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_purchasehistory_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='tracking',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
