# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_purchasehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
