# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20170405_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='street',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='shipping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.Shipping'),
            preserve_default=False,
        ),
    ]
