# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20170406_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='name',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='type',
            field=models.CharField(default='buy', max_length=10),
        ),
    ]
