# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20170408_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
