# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_purchasehistory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='ship_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
