# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_purchasehistory_ship_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('paymenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.PaymentType')),
                ('customer_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('created', models.CharField(max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=16)),
                ('expiry', models.DateField(blank=True)),
            ],
            bases=('payments.paymenttype',),
        ),
    ]
