# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='tracking',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
