# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_auto_20170720_0825'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('reviews', '0002_auto_20170720_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('useful', models.IntegerField(default=0)),
                ('not_useful', models.IntegerField(default=0)),
                ('createdte', models.DateTimeField(default=django.utils.timezone.now)),
                ('fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FacePack')),
                ('ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.PurchaseHistory')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/reviews/')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
