# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_prepack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepack',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
