# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170720_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfacepack',
            name='questionnaire',
        ),
    ]
