# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170801_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_single',
            field=models.DecimalField(decimal_places=2, default=29.0, max_digits=6),
        ),
    ]
