# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(default='buy', max_length=10),
        ),
    ]
