# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('helper', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('why', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facepackwizard.Option')),
            ],
            bases=('facepackwizard.option',),
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facepackwizard.Option')),
            ],
            bases=('facepackwizard.option',),
        ),
        migrations.AddField(
            model_name='questionnaireentry',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Option'),
        ),
        migrations.AddField(
            model_name='questionnaireentry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Question'),
        ),
        migrations.AddField(
            model_name='questionnaireentry',
            name='wizard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.QuestionnaireUserData'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='option',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Option'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Question'),
        ),
    ]
