# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Base')),
            ],
        ),
        migrations.CreateModel(
            name='FacePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_cart', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('createdte', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MixingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('helper', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('facepack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.FacePack')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField()),
                ('facepack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.FacePack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('why', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facepackwizard.Option')),
            ],
            bases=('facepackwizard.option',),
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facepackwizard.Option')),
            ],
            bases=('facepackwizard.option',),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='option',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Option'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Question'),
        ),
        migrations.AddField(
            model_name='custompack',
            name='facepack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.FacePack'),
        ),
        migrations.AddField(
            model_name='custompack',
            name='mixing_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.MixingAgent'),
        ),
        migrations.AddField(
            model_name='custompack',
            name='optional_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Ingredient'),
        ),
        migrations.AddField(
            model_name='custompack',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='skin_concern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinConcern'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='skin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType'),
        ),
        migrations.AddField(
            model_name='mixingagent',
            name='skin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType'),
        ),
        migrations.AddField(
            model_name='base',
            name='skin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType'),
        ),
    ]
