# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireentry',
            old_name='wizard_id',
            new_name='wizard',
        ),
        migrations.AddField(
            model_name='questionnaireuserdata',
            name='createdte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questionnaireuserdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
