# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompack',
            name='createdte',
        ),
        migrations.RemoveField(
            model_name='prepacks',
            name='createdte',
        ),
        migrations.AddField(
            model_name='facepack',
            name='createdte',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
