# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0002_auto_20170223_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrePacks',
            new_name='PrePack',
        ),
        migrations.AddField(
            model_name='base',
            name='skin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType'),
        ),
        migrations.AddField(
            model_name='mixingagent',
            name='skin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.SkinType'),
        ),
    ]
