# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0003_auto_20170223_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
