# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0004_purchases_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='in_cart',
        ),
        migrations.AddField(
            model_name='facepack',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
