# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0005_auto_20170225_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facepack',
            name='createdte',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
