# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facepackwizard', '0006_auto_20170225_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facepack',
            name='id',
        ),
        migrations.AddField(
            model_name='custompack',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facepack',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custompack',
            name='facepack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facepackwizard.FacePack'),
        ),
    ]
