# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0007_auto_20170225_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='facepack',
            name='out_cart',
            field=models.BooleanField(default=False),
        ),
    ]
