# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facepackwizard', '0008_facepack_out_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facepack',
            name='user',
        ),
        migrations.AddField(
            model_name='facepack',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
